### ISSUE TITLE
clicking file attach button freezes Joplin

### ISSUE THREAD

**Issue by kylrth** [flathub/net.cozic.joplin_desktop#107]
version: 2.10.19

Clicking the file attach button causes the entire window to freeze. The cursor continues blinking, so it makes me think the file chooser dialog is supposed to be displayed but is not. I'm guessing this is flatpak-specific but not sure.

**Comment by catsout** [comment]
You may also need to add a issue to https://github.com/flatpak/xdg-desktop-portal/.

**Comment by kylrth** [comment]
Sorry, I think I'm not familiar enough with how specific apps interact with the desktop portal to open a useful issue there. Can you help me?
