### ISSUE TITLE
Corrupted Cursor With Joplin Flatpak 2.12.15 

### ISSUE THREAD

**Issue by bertradio** [flathub/net.cozic.joplin_desktop#124]
Lenovo Duet 5 running Crostini (Linux aarch64/arm).

Only flatpak Joplin works. Have been successfully using Joplin 2.11. Today flatpak updated to 2.12.15 and there are several big problems:

1. The cursor is corrupted. Rather than an arrow, it is a large blurred box with what appears to be an arrow in it. I tried different cursor settings and get the same result.
2. In the upper right corner of the window there are no controls to minimize, maximize or close.

Tried to uninstall and reinstall Joplin flatpak. Install was successful but when I try to run I get this:

`error: app/net.cozic.joplin.desktop/aarch64/master not installed
`
Output of inxi -F:

[Spec.txt](https://github.com/flathub/net.cozic.joplin_desktop/files/12507587/Spec.txt)

Is this a bug? Runnin 2.12.15 on my Linux Mint desktop with no problems... except Print still causes a crash.

How can I revert to an earllier flatpak version or fix this behavior?

Thanks

**Comment by catsout** [comment]
https://docs.flatpak.org/en/latest/tips-and-tricks.html?#downgrading

**Comment by catsout** [comment]
Or use flatseal to disable wayland permission.
