### ISSUE TITLE
Joplin doesn't load

### ISSUE THREAD

**Issue by lucyferu** [flathub/net.cozic.joplin_desktop#145]
Version 2.12.19

After the latest update, when I open the app, nothing loads and it looks severely broken.

![Screenshot_2023-10-30_09-22-13](https://github.com/flathub/net.cozic.joplin_desktop/assets/79750206/379df274-8f2f-42d7-9909-fd654f8e5d96)

[Log](https://pastebin.com/iYkEEy2V) of `inxi -F`.

**Comment by matkaz** [comment]
The last working version for me is https://github.com/flathub/net.cozic.joplin_desktop/commit/cf88e3201c709f92c1edfd7fa1be8e41a34e92b9. You can  revert and pin that version with:
```
$ flatpak update --commit=a4a07cdea05dc330aef5a824ac247c45403c13e98a36cb2fd452078b2ce763ce net.cozic.joplin_desktop
$ flatpak mask net.cozic.joplin_desktop
```

**Comment by XenonSup** [comment]
Same issue.
Here's the [error log](https://pastebin.com/XdaiB49S) 
Can confirm that commit `a4a07cdea05dc330aef5a824ac247c45403c13e98a36cb2fd452078b2ce763ce` works

**Comment by lucyferu** [comment]
Sharing [a part of my error log](https://pastebin.com/K59Gf1dJ) as well.

I've also reverted to older commit and it works. Thanks, @matkaz . 😄

**Comment by xvdd** [comment]
Also having the same issue.

Running it from the command line with `flatpak run --socket=wayland net.cozic.joplin_desktop` works for me with the latest Flathub available version (Gnome Wayland system).

---

If just running `flatpak run net.cozic.joplin_desktop`, it gives me the following errors (and many more)

```
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 22:30:38.272: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:30:38.273: Failed to load module "canberra-gtk-module"
...
```

Which led me to a similar ticket and workaround I posted above https://github.com/flathub/net.cozic.joplin_desktop/issues/10#issuecomment-1737933141

**Comment by catsout** [comment]
Please remove `~/.var/app/net.cozic.joplin_desktop/config/Joplin/GPUCache` and try again.

**Comment by catsout** [comment]
https://github.com/laurent22/joplin/issues/9080

**Comment by xvdd** [comment]
Thanks!

This explains why rollbacking to the previous flatpak version didn't fixed it for me.

**Comment by hivefi** [comment]
Reverting to previous version worked for me too.

**Comment by IlyaBizyaev** [comment]
For me, launching with native Wayland support:
```sh
$ flatpak run --socket=wayland net.cozic.joplin_desktop 
```
also helps.
