### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by ralphocdol** [flathub/net.cozic.joplin_desktop#15]
The title says it all. `notify-send` exists on my system, but it can't seem to access it.
 Below is the screenshot of the logs.
![Joplin Logs, filtered: notif](https://user-images.githubusercontent.com/31056871/127744515-dd02729a-037a-4d45-b119-4d61cb60ef07.png)

I don't know if this will help, but here's a screenshot of the Flatseal showing the Session Bus it talks to:
![Flatseal](https://user-images.githubusercontent.com/31056871/127744588-7d7599d9-51d0-486e-8aee-a22d35ce0153.png)

I'm running **Manjaro** 21.1.0, **KDE** 5.22.4

**Comment by tinywrkb** [comment]
@catsout 

It looks like Joplin might be using [node-notifier](https://github.com/mikaelbr/node-notifier) which implements a wrapper around `notify-send`, and is not using the packaged `libnotify.so`.  
Maybe this should be reported as a bug in `org.electronjs.Electron2.BaseApp`, and we should ask that `notify-send` will be kept and not removed in cleanup step.

**Comment by catsout** [comment]
`notify-send` added.
