### ISSUE TITLE
beta: default wayland icon is shown instaead of the icon

### ISSUE THREAD

**Issue by Wladefant** [flathub/net.cozic.joplin_desktop#153]
![image](https://github.com/flathub/net.cozic.joplin_desktop/assets/79611093/f0df4e3d-0a05-41fe-9c75-877fbcc32f1a)

Here is how to fix this: https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/

**Comment by n3thshan** [comment]
why arent the maintainers paying any attention to this? using xwayland fixes this issue but it is still a bit laggy (in terms of input) compared to native wayland. Please fix this!

**Comment by n3thshan** [comment]
> why arent the maintainers paying any attention to this? using xwayland fixes this issue but it is still a bit laggy (in terms of input) compared to native wayland. The appimage does not suffer from this. Please fix this!

**Comment by nehemiagurl** [comment]
this still an issue, as mentioned in https://github.com/flathub/net.cozic.joplin_desktop/issues/223#issuecomment-2391624715

**Comment by nehemiagurl** [comment]
by the way, there is a workaround around this:
https://youtu.be/Sungl8gWU_8?si=_foyH8Z1mI0eiYUR&t=129
