### ISSUE TITLE
Can't sync until Joplin updated to 2.3.3

### ISSUE THREAD

**Issue by danburd** [flathub/net.cozic.joplin_desktop#16]
Joplin 2.3 updates the sync target so that all clients must update somewhat simultaneously in order to synchronize among each other. See the [forum thread](https://discourse.joplinapp.org/t/attention-sync-version-has-been-changed-in-2-3/19449/52) for an explanation.

I updated my Android client to Joplin 2.3.4, and updated the sync target as well. Now my desktop client won't sync because it's still on 2.2.7. Please update the Flatpak to the latest release, which currently appears to be [2.3.3](https://github.com/laurent22/joplin/releases/tag/v2.3.3), so that Flatpak clients may sync with clients that have already updated to 2.3. Thank you.

**Comment by tinywrkb** [comment]
@catsout the action is failing due to outdated flatpak-builder-tools that do not support v2 nodejs manifest, so you need to update your f-b-t fork.
