### ISSUE TITLE
1.8.5 update to 2.3.5

### ISSUE THREAD

**Issue by langdon** [flathub/net.cozic.joplin_desktop#19]
Flatpak version needs to be updated to latest because there is a database change making this version incompatible with the database for latest.

**Comment by catsout** [comment]
https://flathub.org/apps/details/net.cozic.joplin_desktop  
It has been 2.3.5 for 4 days.

**Comment by langdon** [comment]
yeah.. sorry.. i was using an appimage on this computer and thought it was the flatpak.. ran in to this on a different computer and made a bad assumption.. sorry for the noise
