### ISSUE TITLE
Menu bar stays white in dark mode

### ISSUE THREAD

**Issue by Zahrun** [flathub/net.cozic.joplin_desktop#192]
The menu bar stays white in dark mode for the flatpak version.
![image](https://github.com/flathub/net.cozic.joplin_desktop/assets/10415894/a21e5524-44d2-4053-b710-a857b97f1c26)
It is black in appimage version 
![image](https://github.com/flathub/net.cozic.joplin_desktop/assets/10415894/399e7cf8-2f8f-4128-beb4-45aa60d6499e)

**Comment by n3thshan** [comment]
i found a workaround. this is a general flatpak issue which should have been done by distros by default. Check [this](https://www.reddit.com/r/kde/comments/ujqih9/plasma_consistent_flatpak_theming/) for the tutorial and an explanation.

**Comment by Zahrun** [comment]
Thank you for sharing!

It seems I already had the theme installed
```
flatpak install org.gtk.Gtk3theme.Breeze
Skipping: org.gtk.Gtk3theme.Breeze/x86_64/3.22 is already installed
```

Then I executed the other command
```
sudo flatpak override --system --filesystem=xdg-config/gtk-3.0:ro --filesystem=xdg-config/gtkrc-2.0:ro --filesystem=xdg-config/gtk-4.0:ro --filesystem=xdg-config/gtkrc:ro
```

But sadly, that didn’t fix it on my system. Am I missing anything?

**Comment by n3thshan** [comment]
im sorry. could u provide more info like the distro u r using, etc... also are u using dark mode on kde?

**Comment by Zahrun** [comment]
I’m using Tuxedo OS 3 which has KDE Plasma 6.1.3 on top of a jammy base. I’m using Breeze White during daytime and Breeze Black during nighttime for color scheme. They are derived from Breeze Light and Breeze Dark. I also tried with the normal Breeze Dark, but the issue is also happening then. Application style is Breeze and GTK theme is Breeze. I use everything Breeze apart from cursor theme.

**Comment by Mariocraft95** [comment]
I am having the same issue on Fedora 40 KDE, but my Kubuntu installation of this same flatpak works as intended. 

I am also using Dark mode on KDE

**Comment by Zahrun** [comment]
I found a solution for my system. In Flatseal, give Joplin permission to use wayland (socket=wayland)
