### ISSUE TITLE
Outdated screenshots

### ISSUE THREAD

**Issue by laurent22** [flathub/net.cozic.joplin_desktop#20]
I don't know if it's something you manage here but the screenshot displayed here is an old one:

https://flathub.org/apps/details/net.cozic.joplin_desktop

Any chance it could be updated to a more recent one? There are multiple versions of the new one in png or webp in this folder, under name "home-top-img"

https://github.com/laurent22/joplin/tree/dev/Assets/WebsiteAssets/images

**Comment by catsout** [comment]
https://github.com/flathub/net.cozic.joplin_desktop/commit/2ae44d9b9e1515deaa45f72c95f36e36eec0465c  
I modified few days ago, and plan to push when new version released.  Now it's in master.

**Comment by laurent22** [comment]
That's great, thanks @catsout!
