### ISSUE TITLE
Major Version 3.0.0

### ISSUE THREAD

**Issue by mkalus** [flathub/net.cozic.joplin_desktop#202]
Joplin was released as new major version 3.0.0 just two days ago - it seems to change the way data is synced, since synchronized data sets updated with version 3 are incompatible with version 2.

I would love to see a version 3 release :smile:

**Comment by doubled1** [comment]
Noticed this after an Android device automatically updated the app, which updated the data.  Now it's unavailable from my PCs.

**Comment by Madic-** [comment]
You can use the test build from this pull request: https://github.com/flathub/net.cozic.joplin_desktop/pull/201

**Comment by mkalus** [comment]
Tested it and it looks fine on the first glance.

**Comment by narFnarF** [comment]
There's also always the option to use the official AppImage in the meantime.

**Comment by danktankk** [comment]
> There's also always the option to use the official AppImage in the meantime.

this is what I did.  dropped flathub

**Comment by devtinocodes** [comment]
When will Flatpak version 3 be released?

**Comment by ianchanning** [comment]
I can confirm that running the AppImage script installs 3.0.13 as a separate install that uses the same settings, perfect!

```sh
wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash
```

![image](https://github.com/flathub/net.cozic.joplin_desktop/assets/233318/97de83df-378d-4546-9e2b-ec36bc449720)

**Comment by ianchanning** [comment]
It would still be nice to have the Flatpak upgraded though as otherwise I'll keep having to run the AppImage script for every upgrade instead of `flatpak update`.

**Comment by mbnoimi** [comment]
> There's also always the option to use the official AppImage in the meantime.

I hate AppImage as it hasn't real eco system just like snap or flatpak. I prefer to wait for some days until I get flatpak version

**Comment by letic** [comment]
https://github.com/flathub/net.cozic.joplin_desktop/pull/203 

Run 
`flatpak install --user https://dl.flathub.org/build-repo/115989/net.cozic.joplin_desktop.flatpakref`
Worked for me :+1:

**Comment by mbnoimi** [comment]
> Run
> `flatpak install --user https://dl.flathub.org/build-repo/115989/net.cozic.joplin_desktop.flatpakref`
> Worked for me 👍

Still has `2.14.22 ` after a successful installation


```
$ flatpak install --user https://dl.flathub.org/build-repo/115989/net.cozic.joplin_desktop.flatpakref

net.cozic.joplin_desktop permissions:
    ipc                   network                      cups       pulseaudio       x11       dri       file access [1]
    dbus access [2]       system dbus access [3]

    [1] home
    [2] com.canonical.AppMenu.Registrar, org.freedesktop.Notifications, org.kde.StatusNotifierWatcher
    [3] org.freedesktop.Avahi


        ID                                  Branch            Op            Remote                          Download
 1. [✓] net.cozic.joplin_desktop            test              i             joplin_desktop-origin           120.7 MB / 259.1 MB

Installation complete.
```

**Comment by MarkWieczorek** [comment]
@catsout Could you perhaps merge the new version 3.00 builds? And I wonder if it would be helpful to set up automerge.
