### ISSUE TITLE
Chinese Fonts Don't Render Properly

### ISSUE THREAD

**Issue by FrankAlbella** [flathub/net.cozic.joplin_desktop#21]
In the Flatpak version of Joplin Chinese fonts don't seem to render properly.
Here is what it looks like on the AppImage (and how it's supposed to look like in general):
![image](https://user-images.githubusercontent.com/3748949/132719710-027e3f13-93b5-4c7f-81f6-036551ac907a.png)
And here's what it looks like in the Flatpak version: 
![image](https://user-images.githubusercontent.com/3748949/132719779-642a84d6-4228-4a15-8354-09df530a5b57.png)

**Comment by catsout** [comment]
Try to do:
 `cp ~/.config/fontconfig/* ~/.var/app/net.cozic.joplin_desktop/config/fontconfig/`

**Comment by FrankAlbella** [comment]
> Try to do:
> `cp ~/.config/fontconfig/* ~/.var/app/net.cozic.joplin_desktop/config/fontconfig/`

Did not work. I change `config` to `cache` btw, I assumed this was a typo as neither directory existed otherwise.
