### ISSUE TITLE
DST root cerficate expired, effects syncs.

### ISSUE THREAD

**Issue by jtagcat** [flathub/net.cozic.joplin_desktop#22]
syncs: `failed, reason: certificate has expired`, where the sync server is accessible to the user via other means.

This is very likely due to the [DST root cert expiring](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)

Related: https://github.com/laurent22/joplin/issues/3348

It effectively breaks sync.

**Comment by GabrielMPhi** [comment]
I have the same problem just this morning.

**Comment by Derkades** [comment]
Same issue using the appimage instead of flatpak. It works fine on android.

**Comment by jtagcat** [comment]
Appimage is upstream, I haven't tested the upstream package yet.

**Comment by jtagcat** [comment]
Paging @laurent22 (incoming spam from everyone!)

**Comment by jtagcat** [comment]
Temporary (bad) workaround: Settings → Sync → Ignore TLS failures

**Comment by laurent22** [comment]
Is there something that needs to be changed in the app?

**Comment by PetrVladimirov** [comment]
Same problem is here. Joplin client on Linux (Fedora) doesn't want to sync via valid certificate (Let's Encrypt), Android client syncs. 

Checked the certificate itself - URL opens fine via Firefox (without any warnings)
Checked the Nextcloud address via https://whatsmychaincert.com service - it says chain is valid.

**Comment by PetrVladimirov** [comment]
> Is there something that needs to be changed in the app?

From https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/:
What should you do? For most people, nothing at all! We’ve set up our certificate issuance so your web site will do the right thing in most cases, favoring broad compatibility. If you provide an API or have to support IoT devices, you’ll need to make sure of two things: (1) all clients of your API must trust ISRG Root X1 (not just DST Root CA X3), and (2) if clients of your API are using OpenSSL, they must use version 1.1.0 or later. In OpenSSL 1.0.x, a quirk in certificate verification means that even clients that trust ISRG Root X1 will fail when presented with the Android-compatible certificate chain we are recommending by default.

**Comment by chuglo** [comment]
Same exact issue here. Running Joplin v2.4.9 on Windows 10 client. Let's Encrypt cert. I can confirm the cert IS valid.

**Comment by laurent22** [comment]
To fix your server you can follow these steps: https://github.com/electron/electron/issues/31212#issuecomment-931486784

Hopefully a fix for the desktop app will also be available at some point.

**Comment by AUSBird** [comment]
Can't ignore TLS failures when using S3
Maybe this should be an option

**Comment by laurent22** [comment]
Yes, and I'd accept a PR for it.

**Comment by AUSBird** [comment]
Unless someone beats me to it, I will give it a crack after work :)

**Comment by Felecarpp** [comment]
I have the same issue on Ubuntu 20.04.2 LTS, Joplin 2.4.9, Nextcloud/Let's Encrypt account
I get "reason: certificate has expired" after synthing and I can temporaly fix it with "Ignoring TLS cert errors" also.

**Comment by Derkades** [comment]
It's fixed! https://github.com/laurent22/joplin/releases/tag/v2.5.1

**Comment by jtagcat** [comment]
Flatpak is built out of the latest (stable) [release](https://github.com/laurent22/joplin/releases). Upstream fix is currently a pre-release.
