### ISSUE TITLE
Security warning

### ISSUE THREAD

**Issue by Altonss** [flathub/net.cozic.joplin_desktop#25]
In Gnome Software (in Gnome 41) I get a security warning: "Can acquire arbitrary authorisations". Is this intentional or is the flatpak not correctly configured for security and just runs as root?

**Comment by tinywrkb** [comment]
I haven't looked in Gnome Software's code, but I'm guessing that this is due to the `--talk-name=org.freedesktop.Flatpak` permission.  
This permission was added for external editor support. You can disable it using Flatseal or `flatpak override`.

**Comment by Altonss** [comment]
Here is the screenshot: 
![image](https://user-images.githubusercontent.com/66519591/141508908-b51e33f6-a787-414d-a27e-41d28a5e3eed.png)

**Comment by CheariX** [comment]
See https://github.com/flathub/net.cozic.joplin_desktop/issues/6#issuecomment-808480685

IMHO, this permission should simply be removed.
