### ISSUE TITLE
register mimetype in linux

### ISSUE THREAD

**Issue by langdon** [flathub/net.cozic.joplin_desktop#26]
I am not quite sure what this is a "called" but joplin added a "copy external link" feature to the application. If you get the link you end up with something with a ```joplin://``` uri scheme. I would love to be able to ```xdg-open joplin://x-callback-url/openNote?id=<uuid>```. However, I am not sure if this goes in the flatpak desktop file, somewhere in mimeapps.list, or where exactly.

**Comment by tinywrkb** [comment]
Sounds like an upstream bug. The generated desktop file should have a `MimeType` key with the value `x-scheme-handler/joplin`.  
That's not a Flatpak packaging issue.

**Comment by tinywrkb** [comment]
Also https://github.com/develar/electron-builder/commit/a608142d0096110bc5de1236173de210f441d8bb

**Comment by langdon** [comment]
https://github.com/laurent22/joplin/issues/5728

**Comment by catsout** [comment]
Fixed.
