### ISSUE TITLE
Change default behavior to not break the sandbox

### ISSUE THREAD

**Issue by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [flathub/net.cozic.joplin_desktop#6]
Hi!

Please consider changing the default behavior of the app to not break the sandbox by default. Currently, a first run will pollute the host system with files. Also, consider using the xdg-dirs for mounting, rather than the whole home dir. A user can easily map depending on the needs.

**Comment by jtagcat** [comment]
Joplin shouldn't need $HOME access, and ~/.config/joplin-desktop should be located in the .var/app/net.cozic… dir instead.

**Comment by CheariX** [comment]
I'm additionally wondering whether talking to `org.freedesktop.Flatpak` is really necessary. This is a very powerfull permission.
If this is about editing notes with external editors, `xdg-open` works perfectly in my case.

**Comment by alexmo1997** [comment]
This shouldn't be closed, the flatpak still has filesystem=home permission.
