### ISSUE TITLE
Doesn't work on Asahi Linux Mac M1

### ISSUE THREAD

**Issue by cmalvi** [flathub/net.cozic.joplin_desktop#68]
Joplin was arleady updated to support those machines, but this flatpak version still doesn't work.
Probably the electron version used here isn't the same

**Comment by catsout** [comment]
It's the same.  
What's your joplin version?

**Comment by catsout** [comment]
I mean the joplin version works on your machine.

**Comment by cmalvi** [comment]
Built from source for test

**Comment by catsout** [comment]
So what's the version you built from?

**Comment by cmalvi** [comment]
This but now seems merged https://github.com/laurent22/joplin/pull/6888

**Comment by catsout** [comment]
The Flatpak version is only built from the source code published by Joplin. It will not use the unpublished version, and generally does not patch the source code.  
If this pr is already in pre-release, you can use beta branch https://discourse.flathub.org/t/how-to-use-flathub-beta/2111.
