### ISSUE TITLE
New install can't sync with old sync directory

### ISSUE THREAD

**Issue by ddtuan99** [flathub/net.cozic.joplin_desktop#8]
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Debian 10

## Steps to reproduce

I copy the sync directory to another Linux laptop. Change Synchronization setting properly (set directory path). Click Synchronize but no note has sync and no error apprears.

My sync target on old device use encryptions so i did try enable encryption on new device with same encryption password on old device but nothing changes.

## Describe what you expected to happen
Notes in sync directory are sync (read) by Joplin in new device.

---

Here is [issue](https://github.com/laurent22/joplin/issues/4528) in official Joplin repo. 

Beside that it can creat new note into sync directory but can't sync other encrypted notes.

**Comment by catsout** [comment]
I have check your log, it's seems like the path that you want to sync is at `/media`.  
As this flatpak only have permission on home dir, you need add permission to allow acess `/media`.  
You need:
```
flatpak override net.cozic.joplin_desktop  --filesystem=/media
```
Or use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) set with gui.  

Note: `--filesystem=host` also works.

I think I will add a readme later.

**Comment by ddtuan99** [comment]
@catsout Thank you!

Does `--filesystem=/media` mean Joplin can only access `/media`? Or is it sufficient for Joplin to run only access `/media`?

**Comment by catsout** [comment]
> 
> Does `--filesystem=/media` mean Joplin can only access `/media`? Or is it sufficient for Joplin to run only access `/media`?

No, this command just add access to `/media`.  
The '--filesystem' can use multiple times, will not override others.  
I think [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) is more intuitive.

**Comment by ddtuan99** [comment]
It works fine now.

Thanks for your help and mantaining Flatpark Joplin.
