### ISSUE TITLE
Can't use external editor.

### ISSUE THREAD

**Issue by jtagcat** [flathub/net.cozic.joplin_desktop#9]
I tried patching permissions with flatseal, yet it still doesn't do anything when pressing evoking an external editor. No logs on term.

It doesn't switch to the external editor mode, and doesn't evoke the configured vscodium --wait. Works outside flatpak.

**Comment by catsout** [comment]
try:
```text
Path:
/bin/xdg-open
```
or
```text
Path:
/bin/flatpak-spawn
Arguments:
--host <outside flatpak command>
```

**Comment by catsout** [comment]
The readme is added.    
You can look it for more details.
