### ISSUE TITLE
version 2.10.19 will not launch. 2.10.18 and earlier work

### ISSUE THREAD

**Issue by gorbehnare** [flathub/net.cozic.joplin_desktop#99]
Hello

I just run into issues on two of my systems. Joplin version v 2.10.18 works, but after update to 2.10.19 the application fails to open with following errors:
```
- $ flatpak run net.cozic.joplin_desktop
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 21:51:52.637: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:51:52.638: Failed to load module "canberra-gtk-module"
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```
Version 2.10.18 works as expected. 

OS: Ubuntu 23.04 with the default Gnome desktop (both systems are the same).

**Comment by Ayush1325** [comment]
I have the same issue. I think it is related to this: https://discourse.joplinapp.org/t/no-launch-on-fedora-38/30529/2
